ma_main:
    resource: "@MAMainBundle/Resources/config/routing.yml"
    prefix:   /
    # prefix:   /{_locale}
    # requirements:
    #     _locale: es|en|fr|   # needs to be null in case no /language is provided

ma_user:
    resource: "@MAUserBundle/Resources/config/routing.yml"
    prefix:   /admin
    # prefix:   /{_locale}/admin
    # requirements:
    #     _locale: es|en|fr|   # needs to be null in case no /language is provided

# USERs

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:     /profile
    # prefix:     /{_locale}/profile
    # requirements:
    #     _locale: es|en|fr

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:     /register
    # prefix:     /{_locale}/register
    # requirements:
    #     _locale: es|en|fr

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:     /resetting
    # prefix:     /{_locale}/resetting
    # requirements:
    #     _locale: es|en|fr

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:     /changePassword
    # prefix:     /{_locale}/changePassword
    # requirements:
    #     _locale: es|en|fr


# Redactor 
ma_redactor:
    resource: "@MARedactorBundle/Controller/"
    type:     annotation
    prefix:   /redactor/
