<?php

namespace MA\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AideRepository extends EntityRepository
{
}
