<?php

namespace MA\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findLatestOne() {
		return $this->createQueryBuilder('a')
					->orderBy('a.createdAt', 'DESC')
					->setMaxResults(1)
					->getQuery()
					->getResult();
	}

	public function findAllByDate() {
		return $this->createQueryBuilder('a')
					->orderBy('a.createdAt', 'DESC')
					->getQuery()
					->getResult();
	}

	// public function findLatestOne() {
	// 	return $this->createQueryBuilder('u')
	// 				->where ('u.team = :team')
	// 					->setParameter('team', $team)
	// 				->orderBy('u.lastName', 'ASC')
	// 				->getQuery()
	// 				->getResult();
	// }
}
