<?php

namespace MA\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BGPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BGPhotoRepository extends EntityRepository
{
}
