<?php

namespace MA\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideosRepository extends EntityRepository
{
	public function findLatestOne() {
		return $this->createQueryBuilder('v')
					->orderBy('v.createdAt', 'DESC')
					->setMaxResults(1)
					->getQuery()
					->getResult();
	}

	public function findAllByDate() {
		return $this->createQueryBuilder('v')
					->orderBy('v.createdAt', 'DESC')
					->getQuery()
					->getResult();
	}
}
